baseURL = "https://moumou1.github.io/my-company-site/"
languageCode = 'zh-tw'
title = ' 豪上整體衛浴企業官網'
[params]
  companyName = "豪上衛浴"
  phone = "0933250761"
  email = "gary0612@hotmail.com"
  address = "高雄市苓雅區凱旋二路61號"